ktor {
    deployment {
        port = 8080
        port = ${?PORT}
        port = ${?APP_PORT}
    }
    application {
        modules = [ com.ganeshkulfi.backend.ApplicationKt.module ]
    }
}

storage {
    uploadsDir = ${?UPLOADS_DIR}
}

database {
    host = "localhost"
    host = ${?DB_HOST}
    port = "5432"
    port = ${?DB_PORT}
    name = "ganeshkulfi_db"
    name = ${?DB_NAME}
    user = "ganeshkulfi_user"
    user = ${?DB_USER}
    password = "Ganesh@123"
    password = ${?DB_PASSWORD}
    maxPoolSize = 10
    maxPoolSize = ${?DB_POOL_SIZE}
}

jwt {
    secret = ${?JWT_SECRET}
    issuer = ${?JWT_ISSUER}
    audience = ${?JWT_AUDIENCE}
    realm = "Ganesh Kulfi API"
    expirationTime = 604800000  # 7 days in milliseconds
}
